In [105]:
import numpy as np
import copy

In [106]:
x_train,y_train=np.zeros((10,10)),np.zeros((10,10))
for u in range(10):
    x_train[u][u]=1
    y_train[u][u]=1
print(x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [107]:
weights,bias=[],[]
weights1=np.random.randn(10,10)
weights.append(weights1)
bias1=np.random.randn(10)
bias.append(bias1)

In [108]:
def forward(x_train,y_train,weights,bias):
    outputs=[]
    outputs1=np.zeros((len(x_train),10))
    for data in range(len(x_train)):
        for neurone in range(weights[0].shape[0]):
            #outputs1[data][neurone]=((np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone]) if (np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone])>0 else 0)
            outputs1[data][neurone]=(np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone])
        outputs.append(outputs1)
    return outputs

In [109]:
outputs=forward(x_train,y_train,weights,bias)

In [110]:
print(outputs[0][0])

[-0.68105455  1.7899473   0.58370035  1.05823182  0.33863198 -0.13589217
 -2.95388097 -1.69224331  1.38846451 -0.88129652]


In [151]:
def backprop(x_train,y_train,outputs,wei,bia,alpha=0.001):
    wei=copy.deepcopy(wei)
    bia=copy.deepcopy(bia)
    gradW1=np.zeros(wei[0].shape)
    gradsW1=np.zeros(wei[0].shape)
    gradsB1=np.zeros(bia[0].shape)
    gradMSE=np.zeros(wei[0].shape[0])
    for data in range(len(x_train)):
        for neurone in range(wei[0].shape[0]):
            #gradMSE[neurone]=(((outputs[0][data][neurone]-y_train[data][neurone])*2)/len(wei[0]) if (outputs[0][data][neurone])>0 else 0)
            gradMSE[neurone]=((outputs[0][data][neurone]-y_train[data][neurone])*2)/len(wei[0])
            for w in range(wei[0].shape[1]):
                gradW1[neurone][w]=gradMSE[neurone]*x_train[data][w]
        gradsB1+=gradMSE/len(x_train)
        gradsW1+=gradW1/len(x_train)

    wei[0]=wei[0]-alpha*gradsW1
    bia[0]=bia[0]-alpha*gradsB1
    return wei,bia

In [ ]:
testgrad=np.sum((outputs[0][0]-y_train[0])**2)
print(testgrad)

21.917172162156348


In [140]:
print(be[0][0])

-0.0012462715294683574


In [142]:
w,b=backprop(x_train,y_train,outputs,weights,bias,alpha=0.001)
print(f"Ancien w1 : \n{weights[0][0]}, \nnews:\n {w[0][0]}\n")
print(f"Ancien b1 : \n{bias[0][0]}, \nnews:\n {b[0][0]}")

Ancien w1 : 
[-0.67907812 -0.979183   -1.62661333  1.89758751 -0.34163333  0.58865811
  0.34360027  0.28506144 -0.92264205 -1.19677973], 
news:
 [-0.67924093 -0.97941776 -1.62700332  1.89804246 -0.34171524  0.58879924
  0.34368265  0.28512978 -0.92286326 -1.19706666]

Ancien b1 : 
-0.0019764288373771183, 
news:
 -0.0019034131065862423


In [125]:
def training(x_train,y_train,weights,bias,nb_epochs,alpha=0.001):
    we=copy.deepcopy(weights)
    bi=copy.deepcopy(bias)
    for i in range(nb_epochs):
        outputs=[]
        outputs=forward(x_train,y_train,we,bi)
        MSE=[]
        for data in range(len(x_train)):
            MSE.append(np.sum((outputs[0][data]-y_train[data])**2))
        print(f"MSE totale epoch {i+1}/{nb_epochs} : {np.sum(MSE)}")
        we,bi=backprop(x_train,y_train,outputs,we,bi,alpha)
    outputs=[]
    outputs=forward(x_train,y_train,we,bi)
    MSE=[]
    for data in range(len(x_train)):
        MSE.append(np.sum((outputs[0][data]-y_train[data])**2))
    print(f"MSE finale epoch : {np.sum(MSE)}")
    return we,bi


In [152]:
wi,be=training(x_train,y_train,weights,bias,10000,alpha=0.01)

MSE totale epoch 1/10000 : 238.3788936929961
MSE totale epoch 2/10000 : 237.73971950492654
MSE totale epoch 3/10000 : 237.10319119034682
MSE totale epoch 4/10000 : 236.4692971855728
MSE totale epoch 5/10000 : 235.83802597771856
MSE totale epoch 6/10000 : 235.20936610447282
MSE totale epoch 7/10000 : 234.58330615387706
MSE totale epoch 8/10000 : 233.95983476410385
MSE totale epoch 9/10000 : 233.33894062323685
MSE totale epoch 10/10000 : 232.72061246905136
MSE totale epoch 11/10000 : 232.10483908879567
MSE totale epoch 12/10000 : 231.49160931897413
MSE totale epoch 13/10000 : 230.8809120451301
MSE totale epoch 14/10000 : 230.27273620163086
MSE totale epoch 15/10000 : 229.6670707714529
MSE totale epoch 16/10000 : 229.06390478596825
MSE totale epoch 17/10000 : 228.46322732473175
MSE totale epoch 18/10000 : 227.86502751526933
MSE totale epoch 19/10000 : 227.2692945328673
MSE totale epoch 20/10000 : 226.67601760036217
MSE totale epoch 21/10000 : 226.08518598793208
MSE totale epoch 22/10000 :

In [153]:
outputstest=forward(x_train,y_train,wi,be)
true=0
for nb in range(10):
    print(f"Reel : {nb}, pred : {np.argmax(outputstest[0][nb])}\n")
    if nb==(np.argmax(outputstest[0][nb])):
        true+=1
print(true)

Reel : 0, pred : 0

Reel : 1, pred : 1

Reel : 2, pred : 2

Reel : 3, pred : 3

Reel : 4, pred : 4

Reel : 5, pred : 5

Reel : 6, pred : 6

Reel : 7, pred : 7

Reel : 8, pred : 8

Reel : 9, pred : 9

10


In [124]:
print(outputstest[0][2])

[        nan -0.08030402  0.21411326         nan  1.18433175  0.49000675
 -0.99426126 -0.1090687          nan  1.69641037]
