In [1]:
import numpy as np
import copy

In [2]:
x_train,y_train=np.zeros((10,10)),np.zeros((10,10))
for u in range(10):
    x_train[u][u]=1
    y_train[u][u]=1
print(x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [3]:
weights,bias=[],[]
weights1=np.random.randn(10,10)
weights.append(weights1)
bias1=np.random.randn(10)
bias.append(bias1)

In [10]:
def forward(x_train,y_train,weights,bias):
    outputs=[]
    outputs1=np.zeros((len(x_train),10))
    for data in range(len(x_train)):
        for neurone in range(weights[0].shape[0]):
            outputs1[data][neurone]=((np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone]) if (np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone])>0 else 0)
        outputs.append(outputs1)
    return outputs

In [11]:
outputs=forward(x_train,y_train,weights,bias)

In [12]:
print(outputs[0][0])

[0.0916907  0.         1.31466188 0.         0.         0.2864216
 1.02387332 0.         0.         0.        ]


In [29]:
def backprop(x_train,y_train,outputs,wei,bia,alpha):
    wei=copy.deepcopy(wei)
    bia=copy.deepcopy(bia)
    gradW1=np.zeros(wei[0].shape)
    gradsW1=np.zeros(wei[0].shape)
    gradsB1=np.zeros(bia[0].shape)
    gradMSE=np.zeros(wei[0].shape[0])
    for data in range(len(x_train)):
        for neurone in range(wei[0].shape[0]):
            gradMSE[neurone]=(((outputs[0][data][neurone]-y_train[data][neurone])*2)/len(wei[0]) if (outputs[0][data][neurone])>0 else 0)
            for w in range(wei[0].shape[1]):
                gradW1[neurone][w]=gradMSE[neurone]*wei[0][neurone][w]

        gradsB1+=gradMSE/len(x_train)
        gradsW1+=gradW1/len(x_train)

    wei[0]=wei[0]-alpha*gradW1
    bia[0]=bia[0]-alpha*gradsB1
    return wei,bia

In [19]:
print(weights[0][0])

[ 1.35998687 -1.00953607 -0.83348164  0.18066628  0.12391559  0.06112145
 -1.07966116 -0.05325239  0.93695493 -1.14504284]


In [ ]:
w,b=backprop(x_train,y_train,outputs,weights,bias,alpha=0.001)
print(f"Ancien w1 : \n{weights[0][0]}, \nnews:\n {w[0][0]}\n")
print(f"Ancien b1 : \n{bias[0][0]}, \nnews:\n {b[0][0]}")

Ancien w1 : 
[ 1.35998687 -1.00953607 -0.83348164  0.18066628  0.12391559  0.06112145
 -1.07966116 -0.05325239  0.93695493 -1.14504284], 
news:
 [ 1.35998687 -1.00953607 -0.83348164  0.18066628  0.12391559  0.06112145
 -1.07966116 -0.05325239  0.93695493 -1.14504284]

Ancien b1 : 
-1.268296168048176, 
news:
 -1.2682780018621842


In [31]:
def training(x_train,y_train,outputs,weights,bias,nb_epochs,alpha=0.001):
    for i in range(nb_epochs):
        outputs=forward(x_train,y_train,weights,bias)
        MSE=[]
        for data in range(len(x_train)):
            MSE.append(np.sum((outputs[0][data]-y_train[data])**2))
        print(f"MSE totale epoch {i+1}/{nb_epochs} : {np.sum(MSE)}")
        weights,bias=backprop(x_train,y_train,outputs,weights,bias,alpha)
    outputs=forward(x_train,y_train,weights,bias)
    MSE=[]
    for data in range(len(x_train)):
        MSE.append(np.sum((outputs[0][data]-y_train[data])**2))
    print(f"MSE finale epoch : {np.sum(MSE)}")
    return weights,bias


In [32]:
weights,bias=training(x_train,y_train,outputs,weights,bias,1000,alpha=0.01)

MSE totale epoch 1/1000 : 96.23938024083898
MSE totale epoch 2/1000 : 95.98374112823795
MSE totale epoch 3/1000 : 95.72938514556955
MSE totale epoch 4/1000 : 95.47630361682714
MSE totale epoch 5/1000 : 95.22448795136708
MSE totale epoch 6/1000 : 94.9739296427901
MSE totale epoch 7/1000 : 94.72462026784066
MSE totale epoch 8/1000 : 94.47655148532411
MSE totale epoch 9/1000 : 94.22971503504137
MSE totale epoch 10/1000 : 93.98410273674044
MSE totale epoch 11/1000 : 93.73970648908511
MSE totale epoch 12/1000 : 93.49651826863959
MSE totale epoch 13/1000 : 93.25453012886979
MSE totale epoch 14/1000 : 93.01373419916017
MSE totale epoch 15/1000 : 92.7741226838463
MSE totale epoch 16/1000 : 92.5356878612625
MSE totale epoch 17/1000 : 92.29842208280478
MSE totale epoch 18/1000 : 92.06231777200807
MSE totale epoch 19/1000 : 91.82736742363842
MSE totale epoch 20/1000 : 91.59356360279895
MSE totale epoch 21/1000 : 91.36089894404994
MSE totale epoch 22/1000 : 91.12936615054245
MSE totale epoch 23/10

In [48]:
outputstest=forward(x_train,y_train,weights,bias)
true=0
for nb in range(10):
    print(f"Reel : {nb}, pred : {np.argmax(outputstest[0][nb])}\n")
    if nb==(np.argmax(outputstest[0][nb])):
        true+=1
print(true)

Reel : 0, pred : 2

Reel : 1, pred : 4

Reel : 2, pred : 5

Reel : 3, pred : 2

Reel : 4, pred : 6

Reel : 5, pred : 2

Reel : 6, pred : 4

Reel : 7, pred : 6

Reel : 8, pred : 5

Reel : 9, pred : 7

0
