In [1]:
import numpy as np

In [6]:
x_train,y_train=np.zeros((10,10)),np.zeros((10,10))
for u in range(10):
    x_train[u][u]=1
    y_train[u][u]=1
print(x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [9]:
weights,bias=[],[]
weights1=np.random.randn(10,10)
weights.append(weights1)
bias1=np.random.randn(10)
bias.append(bias1)

In [42]:
def forward(x_train,y_train,weights,bias):
    outputs=np.zeros((len(x_train),10))
    for data in range(len(x_train)):
        for neurone in range(weights[0].shape[0]):
            outputs[data][neurone]+=np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone]
                
    return outputs

In [43]:
outputs=forward(x_train,y_train,weights,bias)

In [ ]:
print(outputs[0])

[-3.80144792 -0.73214585 -1.19495453 -0.26885114  0.1063156   0.76841073
  0.98608697 -1.92146138  0.07680403 -2.2924962 ]


In [39]:
print(outputs.shape)

(10, 10)
