In [179]:
import numpy as np
import copy

In [6]:
x_train,y_train=np.zeros((10,10)),np.zeros((10,10))
for u in range(10):
    x_train[u][u]=1
    y_train[u][u]=1
print(x_train)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [170]:
weights,bias=[],[]
weights1=np.random.randn(10,10)
weights.append(weights1)
bias1=np.random.randn(10)
bias.append(bias1)

In [171]:
def forward(x_train,y_train,weights,bias):
    outputs=[]
    outputs1=np.zeros((len(x_train),10))
    for data in range(len(x_train)):
        for neurone in range(weights[0].shape[0]):
            outputs1[data][neurone]=np.sum((weights[0][neurone]*x_train[data]))+bias[0][neurone]
        outputs.append(outputs1)
    return outputs

In [172]:
outputs=forward(x_train,y_train,weights,bias)

In [173]:
print(outputs[0][0])

[-1.55581598  1.50076786  0.21959973 -2.74593214 -1.09115803  0.12399812
 -0.65121602  0.7474337  -0.02348213 -0.75298735]


In [183]:
def backprop(x_train,y_train,outputs,wei,bia,alpha=0.001):
    wei=copy.deepcopy(wei)
    bia=copy.deepcopy(bia)
    MSE=np.zeros(len(x_train))
    gradW1=np.zeros(wei[0].shape)
    gradsW1=np.zeros(wei[0].shape)
    gradsB1=np.zeros(bia[0].shape)
    gradMSE=np.zeros(wei[0].shape[0])
    for data in range(len(x_train)):
        MSE[data]=(np.sum((outputs[0][data]-y_train[data])**2))/len(x_train[data])
        for neurone in range(wei[0].shape[0]):
            gradMSE[neurone]=((outputs[0][data][neurone]-y_train[data][neurone])*2)/len(wei[0])
            for w in range(wei[0].shape[1]):
                gradW1[neurone][w]=gradMSE[neurone]*wei[0][neurone][w]

        gradsB1+=gradMSE/len(x_train)
        gradsW1+=gradW1/len(x_train)

    wei[0]=wei[0]-alpha*gradW1
    bia[0]=bia[0]-alpha*gradsB1
    return wei,bia

In [184]:
print(weights[0][0])

[ 0.24664903 -0.92972415  0.39608158  0.06388184 -0.41998696 -1.55570926
  0.23681504  0.2075762   1.68103016  0.6902977 ]


In [185]:
w,b=backprop(x_train,y_train,outputs,weights,bias)
print(f"Ancien w1 : \n{weights[0][0]}, \nnews:\n {w[0][0]}\n")
print(f"Ancien b1 : \n{bias[0][0]}, \nnews:\n {b[0][0]}")

Ancien w1 : 
[ 0.24664903 -0.92972415  0.39608158  0.06388184 -0.41998696 -1.55570926
  0.23681504  0.2075762   1.68103016  0.6902977 ], 
news:
 [ 0.2467039  -0.92993096  0.39616968  0.06389605 -0.42008038 -1.55605531
  0.23686772  0.20762238  1.68140408  0.69045124]

Ancien b1 : 
-1.8024650134613776, 
news:
 -1.8020968586821862
